testinfo:
    - id: test_settings_004
      title: 设置-隐私设置相关
      info: 设置-隐私设置相关测试
testcase:
    - element_info: $tab_personal
      find_type: $id
      operate_type: click
      info: 点击'我'按钮

    - element_info: $settings_btn
      find_type: $id
      operate_type: click
      info: 点击'设置'按钮

    - element_info: $privacy_set
      find_type: $text
      operate_type: click
      info: 打开'私信权限'设置

    - element_info: $focus_me
      find_type: $text
      operate_type: click
      info: 点击'我关注的人'

    - element_info: $comm_back
      find_type: $id
      operate_type: click
      info: 返回设置页

    - element_info: $block_list
      find_type: $text
      operate_type: click
      info: 点击'黑名单'

    - element_info: $block_remove
      find_type: $text
      operate_type: ignore
      info: 移除一个用户

    - element_info: $comm_back
      find_type: $id
      operate_type: click
      info: 返回设置页

    - element_info: $privacy_disable
      find_type: $id
      operate_type: click
      info: 关闭隐私账号设置

    - element_info: $watermark_enable
      find_type: $id
      operate_type: click
      info: 开启水印显示昵称

check:
    - element_info: $btn_watermark
      find_type: $text
      check: default_check
      info: 验证隐私设置