testinfo:
    - id: test_settings_001
      title: 设置-基本设置相关
      info: 设置-基本设置相关测试
testcase:
    - element_info: $tab_personal
      find_type: $id
      operate_type: click
      info: 点击'我'按钮

    - element_info: $settings_btn
      find_type: $id
      operate_type: click
      info: 点击'设置'按钮

    - element_info: $net_disable
      find_type: $id
      operate_type: click
      info: 关闭'只在Wi-Fi上传/下载'

    - element_info: $text_confirm
      find_type: $text
      operate_type: click
      info: 确认关闭'只在Wi-Fi上传/下载'

    - element_info: $receive_notice
      find_type: $text
      operate_type: click
      info: 点击'接收通知推送'

    - element_info: $receive_checkbox
      find_type: $id
      operate_type: click
      info: 任意关闭一个通知推送设置

    - element_info: $comm_back
      find_type: $id
      operate_type: click
      info: 返回设置页

    - element_info: $lang
      find_type: $text
      operate_type: click
      info: 点击'已选择语言'

    - element_info: $lang_cho_English
      find_type: $text
      operate_type: click
      info: 选择'English'

    - element_info: $text_save
      find_type: $text
      operate_type: click
      info: 点击'保存'

    - element_info: $settings_btn
      find_type: $id
      operate_type: click
      info: 点击'设置'按钮

    - element_info: $lang_English
      find_type: $text
      operate_type: click
      info: 选择'已选择语言'

    - element_info: $lang_cho_chinese
      find_type: $text
      operate_type: click
      info: 选择'简体中文'

    - element_info: $text_save_english
      find_type: $text
      operate_type: click
      info: 点击'save'

    - element_info: $settings_btn
      find_type: $id
      operate_type: click
      info: 点击'设置'按钮

check:
    - element_info: $lang
      find_type: $text
      check: default_check
      info: 验证返回设置页